services:
  server:
    build: .
    environment:
    - AUTH_ISSUER=${AUTH_ISSUER}
    - AUTH_AUDIENCE=${AUTH_AUDIENCE}
    - GOOGLE_CREDS_BASE64=${GOOGLE_CREDS_BASE64}
    ports:
      - "10000:10000"